<template>
	<div class="insertParagraph">
		<el-form ref="form" :model="form" label-width="80px" :rules="rules" v-loading.fullscreen.lock="fullscreenLoading">
			<el-form-item label="教材" prop="paragraphContent">
				<el-input type="textarea" :rows="4" placeholder="請輸入教材內容" v-model="form.paragraphContent">
				</el-input>
			</el-form-item>
			<el-form-item label="教材類別" prop="paragraphGrade">
				<el-select v-model="form.paragraphGrade" placeholder="請選擇教材類別">
					<el-option label="課外教材" value="0"></el-option>
					<el-option label="國小三年級教材" value="3"></el-option>
					<el-option label="國小四年級教材" value="4"></el-option>
					<el-option label="國小五年級教材" value="5"></el-option>
					<el-option label="國小六年級教材" value="6"></el-option>
				</el-select>
			</el-form-item>
			<el-form-item label="教材來源" prop="paragraphSource">
				<el-input v-model="form.paragraphSource" placeholder="請輸入教材來自第幾單元(例如:第一單元請輸入1)，課外文章輸入該文章的網址"></el-input>
			</el-form-item>
			<el-form-item label="標籤" prop="paragraphHashtag">
				<el-input v-model="form.paragraphHashtag" placeholder="可在此給這段教材一個標籤"></el-input>
			</el-form-item>
			<el-form-item label="產生題目" prop="autoCreate">
				<el-switch on-text="是" off-text="否" v-model="form.autoCreate"></el-switch>
			</el-form-item>
			<el-form-item>
				<el-button type="primary" @click="onSubmit">立即創建</el-button>
				<el-button @click="resetForm('form')">重置</el-button>
			</el-form-item>
		</el-form>
		<el-dialog title="可選新增單字" :visible.sync="dialogTableVisible" :close-on-click-modal="false" @close="dialogClose">
			<el-table :data="gridData" @selection-change="handleSelectionChange" ref="multipleTable">
				<el-table-column type="selection" width="55"></el-table-column>
				<el-table-column property="wordContent" label="單字" min-width="150"></el-table-column>
				<el-table-column property="wordPartofspeech" label="詞性" min-width="150"></el-table-column>
				<el-table-column property="wordInterpretation" label="翻譯" min-width="150"></el-table-column>
			</el-table>
			<div style="margin-top: 20px">
				<el-button @click="wordSubmit">送出</el-button>
				<el-button @click="toggleSelection()">取消选择</el-button>
			</div>
		</el-dialog>

		<el-dialog title="產生考題" :visible.sync="dialogFormVisible" :close-on-click-modal="false">
			<el-form ref="questionform" :model="questionform" label-width="80px">
				<el-form-item label="年級" prop="questionGrade">
					<el-select v-model="questionform.questionGrade" placeholder="請選擇年級">
						<el-option label="課外教材" value="0"></el-option>
						<el-option label="國小三年級" value="3"></el-option>
						<el-option label="國小四年級" value="4"></el-option>
						<el-option label="國小五年級" value="5"></el-option>
						<el-option label="國小六年級" value="6"></el-option>
					</el-select>
				</el-form-item>
				<el-form-item label="題型" prop="questionType">
					<el-select v-model="questionform.questionType" placeholder="請選擇題目類型">
						<el-option label="單選題" value="1"></el-option>
						<el-option label="閱讀測驗" value="2"></el-option>
					</el-select>
				</el-form-item>
				<el-form-item label="標籤" prop="questionHashtag">
					<el-input v-model="questionform.questionHashtag" placeholder="可在此給題目一個標籤"></el-input>
				</el-form-item>
				<el-form-item label="題目" prop="content">
					<template v-for="(r,index) in questionform.content">
						<a :key="r.content" href="javascript:void(0)" v-on:click="selectWord(r,index)">{{r.content + ' '}}</a>
					</template>
				</el-form-item>

				<el-form-item v-for="(answer, index) in questionform.answers" :label="'答案' + (index+1)" :key="answer.key" :prop="'answers.' + index + '.rightvalue'" :rules="{required: true, message: '答案不能为空', trigger: 'blur'}">
					<el-input v-model="answer.rightvalue">
						<template slot="prepend">正確答案</template>
					</el-input>
					<el-input v-model="answer.wrongvalue1">
						<template slot="prepend">錯誤答案</template>
					</el-input>
					<el-input v-model="answer.wrongvalue2">
						<template slot="prepend">錯誤答案</template>
					</el-input>
					<el-input v-model="answer.wrongvalue3">
						<template slot="prepend">錯誤答案</template>
					</el-input>
					<el-button @click.prevent="removeAnswer(answer)">删除</el-button>
				</el-form-item>
				<el-form-item>
					<el-button type="primary" @click="questionSubmit">立即創建</el-button>
				</el-form-item>
			</el-form>
		</el-dialog>
	</div>
</template>
<script>
import qs from 'qs'
import {lessonPlan_url,translate_url,question_insert_url,word_insert_url,question_autoGenerated_url,paragraph_insert_url} from '@/config/api'	 
export default {
	name: 'insertParagraph',
	data() {
		return {
			labelPosition: 'right',
			form: {
				paragraphContent: '',
				paragraphHashtag: '',
				paragraphGrade: '',
				paragraphSource: '',
				autoCreate: 'false',
				createBy: this.$route.params.user,
			},
			auto:'false',
			questionform: {
				questionGrade: '',
				questionType: '',
				questionHashtag: '',
				content: [{
					content: '1',
				}, {
					content: '2',
				}],
				answers: [],
				ans: '',
				questionContent: '',
				questionParagraphId: '',
				createBy: this.$route.params.user,
				// answers: [{
				// 	rightvalue: '',
				// 	wrongvalue1: '',
				// 	wrongvalue2: '',
				// 	wrongvalue3: '',
				// }],
			},
			gridData: [{
				wordContent: '',
				wordPartofspeech: '',
				wordInterpretation: '',
			}],
			dialogTableVisible: false,
			dialogFormVisible: false,
			test: 0,
			multipleSelection: [],
			rules: {
				paragraphContent: [
					{ required: true, message: '請輸入教材', trigger: 'blur' },
				],
				paragraphGrade: [
					{ required: true, message: '請選擇教材類別', trigger: 'change' }
				]

			},
			fullscreenLoading: false,
			anscount: 1,
			countIndex: [],
		}
	},
	methods: {
		resetForm(formName) {
			this.$refs[formName].resetFields();
		},
		onSubmit() {
			this.auto = false
			this.$refs.form.validate((valid) => {
				if (valid) {
					this.fullscreenLoading = true;
					this.insertParagraph()
					if (this.form.autoCreate == true) {
						this.autoCreate()
						this.auto = true
					}
				} else {
					return false
				}
			});
		},
		dialogClose() {
			if (this.auto == true) {
				this.dialogFormVisible = true
			}
		},
		autoCreate() {
			this.$http.post(question_autoGenerated_url, qs.stringify(this.form))
				.then(response => {
					console.log(response.data.data)
					this.questionform.content = response.data.data.data
					this.questionform.questionGrade = response.data.data.grade
					this.questionform.questionHashtag = response.data.data.hashtag
					this.questionform.questionType = response.data.data.type.toString()
				})

		},
		insertParagraph() {
			this.$http.post(paragraph_insert_url, qs.stringify(this.form))
				.then(response => {
					this.gridData = response.data.data.wordList
					this.questionform.questionParagraphId = response.data.data.ParagraphId
					this.getOtherAttributes()
					if (response.data.code == 0) {
						this.$message({
							type: 'success',
							message: '新增成功'
						});
						this.resetForm('form')
					}
				})
				.catch(error => {
					console.log(error);
					this.$message({
						type: 'error',
						message: '新增失敗'
					});
				});
		},
		selectWord(r, index) {
			if (this.countIndex.includes(index)) {

			} else {
				this.questionform.answers.push({
					rightvalue: r.content,
					wrongvalue1: r.falseAnsList[0],
					wrongvalue2: r.falseAnsList[1],
					wrongvalue3: r.falseAnsList[2],
					key: Date.now()
				})
				r.content = '_' + this.anscount + '_'
				this.countIndex.push(index)
				this.anscount++
			}
		},
		removeAnswer(item) {
			var index = this.questionform.answers.indexOf(item)
			if (index !== 0) {
				this.questionform.content[this.countIndex[index]].content = item.rightvalue
				this.questionform.answers.splice(index, 1)
				this.countIndex.splice(index, 1)
				this.anscount--

			}
		},
		wordSubmit() {
			var self = this
			let promises = [];
			this.multipleSelection.forEach(function(element) {
				promises.push(self.$http.post(word_insert_url, qs.stringify(element)))
			})
			this.$http.all(promises).then(this.$http.spread((...args) => {
				this.$message({
					type: 'success',
					message: '新增成功'
				});

			}))
			this.dialogTableVisible = false
		},
		questionSubmit() {
			this.fullscreenLoading = true;
			var ans = this.questionform.answers
			var temp = this.questionform.content
			var content = ''
			for (var i = 0; i < temp.length; i++) {
				if ((i + 1) < temp.length && temp[i + 1].content != ',' && temp[i + 1].content != '.' && temp[i + 1].content != '?') {
					content = content + temp[i].content + ' '
				} else {
					content = content + temp[i].content
				}
			}
			this.questionform.questionContent = content
			this.questionform.ans = JSON.stringify(ans)
			this.$http.post(question_insert_url, qs.stringify(this.questionform))
				.then(response => {
					this.fullscreenLoading = false;
					this.dialogFormVisible = false;
					if (response.data.code == 0) {
						this.$message({
							type: 'success',
							message: '新增成功'
						});
					}
				}).catch(error => {
					this.fullscreenLoading = false;
					console.log(error);
					this.$message({
						type: 'error',
						message: '新增失敗'
					});
				});

		},
		getInterpretation(element) {
			this.$http.get(translate_url + element.wordContent)
				.then(response => {
					element.wordInterpretation = response.data.text[0]
				})
		},
		getOtherAttributes() {
			var self = this;
			this.gridData.forEach(function(element) {
				self.getInterpretation(element)
				element.wordGrade = self.form.paragraphGrade
				element.wordSource = self.form.paragraphSource
				element.createBy = self.$route.params.user
			});
			this.fullscreenLoading = false;
			this.dialogTableVisible = true
		},
		toggleSelection() {
			this.$refs.multipleTable.clearSelection();
		},
		handleSelectionChange(val) {
			this.multipleSelection = val;
		},
		createQuestion() {
			// trigger() {
			// 	var self = this;
			// 	self.allert(function(data) {
			// 		self.notification(data)
			// 	});
			// },
			// allert: function(callback) {
			// 	var self=this;
			// 	setTimeout(()=>{
			// 	console.log(this.test);
			// 	},1000);
			// 	 callback("123");

			// },
			// notification: function(data) {
			// 	console.log(data);
			// },

		}
	}
}

</script>
<style lang="scss" scoped>
.insertParagraph {
	position: relative;
	padding: 32px 32px 24px 32px;
	background-color: #ffffff;
	border-radius: 5px;
	box-shadow: 2px 3px 4px rgba(0, 0, 0, .2);
}

.el-select {
	display: block;
}
</style>